# Generated by Django 5.2.4 on 2025-07-25 12:28

import django.db.migrations.operations.special
import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models



class Migration(migrations.Migration):

    replaces = [('core', '0001_initial'), ('core', '0002_userprofile_date_created_userprofile_date_updated_and_more'), ('core', '0003_sensorreading'), ('core', '0004_sensorreading_deduplicationid'), ('core', '0005_userprofile_alert_email_enabled'), ('core', '0006_alter_device_serial_number'), ('core', '0007_alter_device_serial_number_and_more'), ('core', '0008_remove_device_unique_serial_number_per_user_and_more'), ('core', '0009_auto_20250724_1442'), ('core', '0010_alter_device_users'), ('core', '0011_alter_device_serial_number')]

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Device',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_created', models.DateTimeField(auto_now_add=True)),
                ('date_updated', models.DateTimeField(auto_now=True)),
                ('serial_number', models.CharField(max_length=64)),
                ('users', models.ManyToManyField(related_name='devices', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='SensorReading',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_created', models.DateTimeField(auto_now_add=True)),
                ('date_updated', models.DateTimeField(auto_now=True)),
                ('value', models.FloatField()),
                ('rssi', models.FloatField()),
                ('timestamp', models.DateTimeField()),
                ('device', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='readings', to='core.device')),
                ('deduplicationId', models.CharField(default=None, max_length=64, unique=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('address', models.CharField(blank=True, max_length=255)),
                ('phone', models.CharField(blank=True, max_length=32)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to=settings.AUTH_USER_MODEL)),
                ('date_created', models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now)),
                ('date_updated', models.DateTimeField(auto_now=True)),
                ('alert_email_enabled', models.BooleanField(default=True)),
            ],
        ),
        migrations.AlterField(
            model_name='device',
            name='users',
            field=models.ManyToManyField(blank=True, related_name='devices', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='device',
            name='serial_number',
            field=models.CharField(max_length=64, unique=True),
        ),
    ]
