# Generated by Django 5.2.4 on 2025-07-29 10:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_squashed_0011_alter_device_serial_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='device',
            name='name',
            field=models.CharField(default='device', max_length=100),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='sensorreading',
            name='deduplicationId',
            field=models.CharField(max_length=64, unique=True),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='date_created',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
